Able to install from npm
i-break-codes/logerr pull request #22
Opened 2016-10-25 04:01 UTC by Grawl

2016-10-26 20:31 UTC, i-break-codes requested changes

2016-10-26 20:31 UTC, i-break-codes commented on package.json
> +  "main": "logger.js",
logerr.js :) Rest is fine..

2016-10-27 01:30 UTC, Grawl commented on package.json
> +  "main": "logger.js",
done

2016-10-27 01:30 UTC, Grawl commented
#11

2016-10-27 06:48 UTC, i-break-codes commented
Hey thanks, can you fix the conflicts please?

2016-11-03 04:11 UTC, i-break-codes commented
Gentle reminder!

2016-11-03 06:55 UTC, Grawl commented
Oh sorry @i-break-codes I committed right on GitHub because I have not such a time just for now. Maybe on next week or later.

2016-11-04 15:27 UTC, ghosh commented
@i-break-codes Seems like there is just a minor conflict in the readme. Should not be much of a problem to resolve easily. Looking forward to be able to install from npm! 😀

2016-11-04 16:06 UTC, Grawl commented
@ghosh you can use my fork for now

2016-11-04 20:36 UTC, i-break-codes approved these changes

2016-11-04 20:38 UTC, i-break-codes commented
@ghosh Yea, kinda makes sense me resolving the conflicts on his behalf as it's pretty straight forward.. will do it by tomorrow. Cheers \m/

2016-11-08 07:25 UTC, merged

2016-11-08 07:26 UTC, Grawl commented
Hooray!

2016-11-08 07:27 UTC, i-break-codes commented
Done @ghosh @Grawl, thanks for contributing 👍 ...

2016-11-08 07:30 UTC, Grawl commented
Glad to help you!